version: '2.4'

services:
  airsane:
    container_name: airsane
    build:
      context: .
    restart: unless-stopped
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /run/dbus:/run/dbus
      - ./drivers:/opt/drivers
    privileged: True
    ports:
      - 8090:8090/tcp
